services:
  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: unless-stopped
    command: http n8n:5678
    environment:
      - NGROK_AUTHTOKEN=token
    ports:
      - "4040:4040"
    networks:
      - infra_networks

networks:
  infra_networks:
    driver: bridge


